#!/usr/bin/python

import RpmQuality

import sys
import os
import re
import datetime


def usage():
    progname = os.path.basename(__file__)
    print("Usage:")
    print("%s [-h]                               prints help" % progname)
    print("%s package [ package, package, ... ]  perform tests" % progname)
    exit(1)


def print_result(result):
    """
    Prints results well formated.
    """
    print("Total score: %s" % result["score"])
    for module_data in result["results"]:
        print("Module %s score: %s" % (module_data["module"], module_data["score"]))
        print("Module %s logfile: %s" % (module_data["module"], module_data["logfile"]))


def main():
    verbose = False
    packages = []
    scl_name = None
    logs = "/var/tmp/rpmquality%s" % datetime.datetime.now().strftime('%Y%m%d%H%M%S%Z')

    # parsing arguments
    args = list(sys.argv)
    args.reverse()
    args.pop()
    while args:
        arg = args.pop()
        if arg == "-h" or arg == "--help":
            usage()
        elif arg == "-v" or arg == "--verbose":
            verbose = True
        elif args and (arg == "-l" or arg == "--logs"):
            logs = args.pop()
        elif args and (arg == "-s" or arg == "--scl"):
            scl_name = args.pop()
        else:
            if os.path.isfile(arg) and re.match(r".*\.rpm$", arg):
                packages.append(arg)
            elif os.path.isdir(arg):
                for f in os.listdir(arg):
                    if re.match(r".*\.rpm$", f):
                        packages.append(os.path.join(arg, f))
            else:
                print("Argument %s is not rpm nor valid argument." % arg)
                usage()

    if not packages:
        print("No packages specified.")
        usage()

    if not scl_name:
        regexp = re.compile(r"^(\w+)-build.*")
        for pkg in packages:
            m = regexp.match(os.path.basename(pkg))
            if m:
                scl_name = m.group(1)
                break
        regexp = re.compile(r"^(\w+)-.*")
        pkg = os.path.basename(packages[0])
        m = regexp.match(pkg)
        if m:
            scl_name = m.group(1)

    print("Verbose: %s" % verbose)
    print("SCL name: %s" % scl_name)
    print("Logs location: %s" % logs)
    print("Packages:")
    for rpm in packages:
        print(rpm)

    rp = RpmQuality.RpmQuality(packages=packages, scl_name=scl_name,
                               logs_location=logs
                               #,
                               #extra_modules_dir="softwarecollectios_modules",
                               #extra_modules={"UserFavour": 60},
                               #user_id="pepa"
                               )
    result = rp.performAll()
    print_result(result)


if __name__ == "__main__":
    main()



